### ISSUE TITLE
无法直接运行

### ISSUE THREAD

**Issue by nsmccoder** [YushenLi807/WWW24-RAT#2]
我将数据集放置在data文件夹下的，也就是Readme里面的数据，下载后根据名字一一放在对应的目录下面，没有动configs文件夹：
但是仍然报错了：
Traceback (most recent call last):
  File "run_expid.py", line 36, in <module>
    params = load_config(args['config'], experiment_id)
  File "/home/lpd/projects/WWW24-RAT-main/WWW24-RAT-main/fuxictr/utils.py", line 50, in load_config
    dataset_params = load_dataset_config(config_dir, params['dataset_id'])
  File "/home/lpd/projects/WWW24-RAT-main/WWW24-RAT-main/fuxictr/utils.py", line 64, in load_dataset_config
    raise RuntimeError('dataset_id={} is not found in config.'.format(dataset_id))
RuntimeError: dataset_id=kkbox_x1_10fold_retrieval is not found in config.

期待收到您的回复

**Comment by gimpong** [comment]
kkbox_x1_10fold_retrieval在[configs/datasets/kkbox_x1.yaml](https://github.com/YushenLi807/WWW24-RAT/blob/413d26f3d9df0d52537cc84cebf60845a51f18ca/configs/datasets/kkbox_x1.yaml#L62)中是存在的，而命令行报找不到，应该是文件路径没对应上。有可能你执行命令的工作目录不是 /home/lpd/projects/WWW24-RAT-main/WWW24-RAT-main/ 而是 /home/lpd/projects/WWW24-RAT-main/，这样的话相对路径" ./some_folder/ "指向的位置就不对了。你可以再检查一下，看起来应该不是代码的问题。

**Comment by CHENCHEN-MO** [comment]
我也遇到这个问题了，    
if not dataset_configs:
        dataset_configs = glob.glob(os.path.join(config_dir, 'dataset_config/*.yaml'))

我运行的是：python run_expid.py --config ./configs/RAT_m2/tmall_x1_002 --expid  RAT_m2_tmall_x1_002_retrieval --gpu 0
但是看起来根本就没有dataset_config这个文件夹，请问楼主解决这个问题了吗

**Comment by gimpong** [comment]
> 我也遇到这个问题了， if not dataset_configs: dataset_configs = glob.glob(os.path.join(config_dir, 'dataset_config/*.yaml'))
> 
> 我运行的是：python run_expid.py --config ./configs/RAT_m2/tmall_x1_002 --expid RAT_m2_tmall_x1_002_retrieval --gpu 0 但是看起来根本就没有dataset_config这个文件夹，请问楼主解决这个问题了吗

你好，可能是路径写的有点问题，dataset configs应该是在[这里](https://github.com/YushenLi807/WWW24-RAT/tree/main/configs/datasets)，你试试重新调整路径或者更改代码里的路径名称，看下是否能解决问题。

**Comment by CHENCHEN-MO** [comment]
感谢作者回复！我把配置修改成dataset_configs = glob.glob(os.path.join(config_dir, '../../datasets/*.yaml'))这里不会报错了，
但是我通过BaiduDisk下载到的Tmall_002_retrieval这个数据集放置到data文件下下，执行的时候报错：OSError: Unable to synchronously open file (truncated file: eof = 65536, sblock->base_addr = 0, stored_eof = 1523907824)，是因为test.h5这个文件只有64kb，但是文件声明里有1.5G，导致加载失败了

**Comment by gimpong** [comment]
你好，我看了一下，应该是当时文件没上传成功。可以用Tmall_002文件夹的test.h5代替。

**Comment by CHENCHEN-MO** [comment]
好的大佬，我替换试试
